Change how the signtool is found

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,8 +17,17 @@ runs:
     - name: Setup signtool environment variable
       if: runner.os == 'Windows'
       run: |
-       $signTools =  (Get-ChildItem -Recurse 'C:\Program Files (x86)\Windows Kits\10\bin' -Filter signtool.exe  | Where-Object FullName -like "*\x86\*" | Sort-Object -Descending)
-       echo "SIGNTOOL=$($signTools[0].FullName)" >> $Env:GITHUB_ENV
+        $sdkMajor = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\[0-9]*' | Select-Object -Property Name, @{Name = 'SortIndex'; Expression = {[int]$_.Name} } | Sort-Object -Descending -Property SortIndex | Select-Object -ExpandProperty Name -First 1
+        $sdkVersion = Get-ChildItem "C:\Program Files (x86)\Windows Kits\$sdkMajor\bin\[0-9]*" | Sort-Object -Descending $_.FullName | Select-Object -ExpandProperty Name -First 1
+        $signTool = "C:\Program Files (x86)\Windows Kits\{0}\bin\{1}\x86\signtool.exe" -f $sdkMajor,$sdkVersion
+
+        if (Test-Path -Path $signTool) {
+          echo "SIGNTOOL=$signTool" >> $Env:GITHUB_ENV
+        }
+        else {
+          echo "Sign tool not found"
+          exit 1
+        }
       shell: pwsh
     - name: Verify executable signatures
       if: runner.os == 'Windows'
